name: JackDeng-action-confluence-sync
description: 'Action confluence sync that can be used to publish markdown documents to confluence.'
author: 'hadenlabs-jackdeng'
inputs:
  confluence_url:
    description: base url of confluence
    required: true
  confluence_username:
    description: confluence username
    required: true
  confluence_token:
    description: token of user
    required: true
  files:
    description: files to sync
    required: true

runs:
  using: 'composite'
  steps:
    - name: Sync files to confluence.
      uses: addnab/docker-run-action@v3
      with:
        image: jackfirework/markl:latest
        options: -v ${{ github.workspace }}:/github/workspace --workdir /github/workspace
        run: |
          echo "username = '${{ inputs.confluence_username }}'" >> ./config.toml
          echo "password = '${{ inputs.confluence_token }}'" >> ./config.toml
          echo "base_url = '${{ inputs.confluence_url }}'" >> ./config.toml

          for file in ${{ inputs.files }}; do
            if ! grep -F "<!-- Space:" $file; then
                continue
            fi
            echo -n "-L $file " >> temp
          done
          targets = $(cat temp) 
          echo "> Sync $targets";
          mark --config ./config.toml -k ${targets} || exit 1;

branding:
  icon: 'check-circle'
  color: 'green'
